### ISSUE TITLE
Add classes to any other DOM element

### ISSUE THREAD

**Issue by mprofitl** [yowainwright/stickybits#101]
I would like to be able to react all over a page to changes of the sticky status. Therefore it would be wonderful if I could give each stickybit instance a name and tell to which other DOM element classes should be added, depending on the sticky status. 

```
stickybits("selector", {
   useGetBoundingClientRect: true,
   name: 'customname',
   addClassesTo: 'anotherselector'
});
```

The anotherselector would then receive the classes `js-is-sticky-customname`, 
`js-is-stuck-customname` and `js-stickybit-parent-customname`.

I could then style _any_ other element: `.anotherselector.js-is-stuck-customname .anyelement`

This feature request is the same as in the old repository: https://github.com/dollarshaveclub/stickybits/issues/101

**Comment by yowainwright** [comment]
@mprofitl, this issue has been discussed. Here's why we can't do [that](https://github.com/dollarshaveclub/stickybits/issues/584). 

~Thanks
