### ISSUE TITLE
Destroy feature?

### ISSUE THREAD

**Issue by simplenotezy** [yowainwright/stickybits#65]
**Is your feature request related to a problem? Please describe.**
I am developing for a SPA and weird things happen on page change -- it seems to work on current page, but when switching to other pages that use same components that have sticky, then it seems to create some issues.

**Describe the solution you'd like**
A way to destroy stickybits on `beforeDestroy` callbacks.

**Comment by yowainwright** [comment]
@simplenotezy sorry for the quick response. Happy to chat more. 

Does this do the trick? https://github.com/yowainwright/stickybits#stickybits-cleanup

Could you provide a CodePen or something? Thanks!
