### ISSUE TITLE
Where is applyStyle?

### ISSUE THREAD

**Issue by ZorGleH** [yowainwright/stickybits#73]
Hi,

There is an [`applyStyle`](https://github.com/yowainwright/stickybits#stickybits-applystyle) option in the documentation, but I can't find it in the code.

**Comment by GeekJosh** [comment]
https://github.com/yowainwright/stickybits/blob/0f74ffa1b88e7c696d321fa430a946c5ca0c02d9/src/stickybits.js#L406

**Comment by yowainwright** [comment]
Thanks @GeekJosh
